import React, { useRef, useMemo, useState, useEffect } from 'react';
import { useFrame } from '@react-three/fiber';
import { Html } from '@react-three/drei';
import * as THREE from 'three';
import gsap from 'gsap';

const cardData = [
  {
    eyebrow: "Birth Chart",
    title: "Birth Chart",
    glyph: "☉",
    desc: "Decode the exact alignment of the planets at the second of your birth. An AI-synthesized blueprint revealing your core personality, career destiny, and potentials.",
    actionName: "Generate Map",
    index: "I",
    baseAngle: 0,
    sigil: `<circle cx="80" cy="80" r="55" fill="none" stroke="currentColor" stroke-width="0.6" stroke-dasharray="3 6"/>
            <circle cx="80" cy="80" r="35" fill="none" stroke="currentColor" stroke-width="0.4"/>
            <line x1="80" y1="25" x2="80" y2="135" stroke="currentColor" stroke-width="0.5"/>
            <line x1="25" y1="80" x2="135" y2="80" stroke="currentColor" stroke-width="0.5"/>
            <line x1="41" y1="41" x2="119" y2="119" stroke="currentColor" stroke-width="0.3" opacity="0.6"/>
            <line x1="119" y1="41" x2="41" y2="119" stroke="currentColor" stroke-width="0.3" opacity="0.6"/>
            <circle cx="80" cy="25" r="2.5" fill="currentColor"/>
            <circle cx="80" cy="135" r="2.5" fill="currentColor"/>
            <circle cx="25" cy="80" r="2.5" fill="currentColor"/>
            <circle cx="135" cy="80" r="2.5" fill="currentColor"/>
            <circle cx="80" cy="80" r="5" fill="none" stroke="currentColor" stroke-width="1.2"/>`,
    theme: {
      glow: '#FFD700',
      rgb: '255, 215, 0',
      streakColor: 'rgba(255, 215, 0, 0.38)',
      medallionBg: 'rgba(255, 215, 0, 0.08)',
      medallionBorder: 'rgba(255, 215, 0, 0.25)'
    },
    review: {
      user: "Seraphina K.",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=60&auto=format&fit=crop&q=80",
      text: "Identified placements I'd never been able to put into words."
    }
  },
  {
    eyebrow: "Arcane Gem",
    title: "Celestial Diamond",
    glyph: "♢",
    desc: "A pure crystalline structure generated by neural alignments. Peer into its facets to witness the convergence of light and shadow in real-time.",
    actionName: "Peer Into Gem",
    index: "II",
    baseAngle: Math.PI / 2,
    sigil: `<polygon points="60,40 100,40 120,65 80,120 40,65" fill="none" stroke="currentColor" stroke-width="0.8"/>
            <line x1="40" y1="65" x2="120" y2="65" stroke="currentColor" stroke-width="0.8"/>
            <line x1="60" y1="40" x2="55" y2="65" stroke="currentColor" stroke-width="0.5"/>
            <line x1="60" y1="40" x2="80" y2="65" stroke="currentColor" stroke-width="0.5"/>
            <line x1="100" y1="40" x2="80" y2="65" stroke="currentColor" stroke-width="0.5"/>
            <line x1="100" y1="40" x2="105" y2="65" stroke="currentColor" stroke-width="0.5"/>
            <line x1="55" y1="65" x2="80" y2="120" stroke="currentColor" stroke-width="0.5"/>
            <line x1="80" y1="65" x2="80" y2="120" stroke="currentColor" stroke-width="0.5"/>
            <line x1="105" y1="65" x2="80" y2="120" stroke="currentColor" stroke-width="0.5"/>
            <circle cx="80" cy="120" r="1.5" fill="currentColor"/>
            <circle cx="40" cy="65" r="1.5" fill="currentColor"/>
            <circle cx="120" cy="65" r="1.5" fill="currentColor"/>
            <circle cx="60" cy="40" r="1.5" fill="currentColor"/>
            <circle cx="100" cy="40" r="1.5" fill="currentColor"/>`,
    theme: {
      glow: '#FFFFFF',
      rgb: '255, 255, 255',
      streakColor: 'rgba(255, 255, 255, 0.38)',
      medallionBg: 'rgba(255, 255, 255, 0.08)',
      medallionBorder: 'rgba(255, 255, 255, 0.25)'
    },
    review: {
      user: "Marcus V.",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=60&auto=format&fit=crop&q=80",
      text: "Spookily accurate. The AI synthesis feels like a real master oracle."
    }
  },
  {
    eyebrow: "Horoscope",
    title: "Daily Horoscope",
    glyph: "☾",
    desc: "Track custom planetary transits computed for your unique coordinates. Discover how today's lunar cycles and solar houses impact your mood and path.",
    actionName: "Read Forecast",
    index: "III",
    baseAngle: Math.PI,
    sigil: `<circle cx="80" cy="80" r="60" fill="none" stroke="currentColor" stroke-width="0.4" stroke-dasharray="1 4"/>
            <circle cx="80" cy="20" r="2.5" fill="currentColor"/>
            <circle cx="132" cy="50" r="2.5" fill="currentColor"/>
            <circle cx="132" cy="110" r="2.5" fill="currentColor"/>
            <circle cx="80" cy="140" r="2.5" fill="currentColor"/>
            <circle cx="28" cy="110" r="2.5" fill="currentColor"/>
            <circle cx="28" cy="50" r="2.5" fill="currentColor"/>
            <polygon points="80,20 132,50 132,110 80,140 28,110 28,50" fill="none" stroke="currentColor" stroke-width="0.5"/>
            <line x1="80" y1="20" x2="132" y2="110" stroke="currentColor" stroke-width="0.3" opacity="0.5"/>
            <line x1="80" y1="20" x2="28" y2="110" stroke="currentColor" stroke-width="0.3" opacity="0.5"/>
            <line x1="132" y1="50" x2="28" y2="110" stroke="currentColor" stroke-width="0.3" opacity="0.5"/>
            <line x1="132" y1="50" x2="28" y2="50" stroke="currentColor" stroke-width="0.3" opacity="0.5"/>
            <line x1="132" y1="110" x2="28" y2="50" stroke="currentColor" stroke-width="0.3" opacity="0.5"/>
            <line x1="80" y1="140" x2="132" y2="50" stroke="currentColor" stroke-width="0.3" opacity="0.5"/>
            <circle cx="80" cy="80" r="10" fill="none" stroke="currentColor" stroke-width="0.7"/>`,
    theme: {
      glow: '#A855F7',
      rgb: '168, 85, 247',
      streakColor: 'rgba(168, 85, 247, 0.38)',
      medallionBg: 'rgba(168, 85, 247, 0.08)',
      medallionBorder: 'rgba(168, 85, 247, 0.25)'
    },
    review: {
      user: "Elena R.",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=60&auto=format&fit=crop&q=80",
      text: "Now my default morning check-in. The transit accuracy is unmatched."
    }
  },
  {
    eyebrow: "Moon Tracker",
    title: "Moon Tracker",
    glyph: "◐",
    desc: "Align your manifestation rituals with active lunar phases. Monitor exact illumination percentages, house transits, and void-of-course windows.",
    actionName: "Track Phase",
    index: "IV",
    baseAngle: (3 * Math.PI) / 2,
    sigil: `<circle cx="80" cy="80" r="52" fill="none" stroke="currentColor" stroke-width="0.5"/>
            <path d="M80,28 A52,52 0 0,1 80,132" fill="none" stroke="currentColor" stroke-width="1.2"/>
            <path d="M80,28 Q50,80 80,132" fill="none" stroke="currentColor" stroke-width="0.5" opacity="0.7"/>
            <path d="M80,28 Q110,80 80,132" fill="none" stroke="currentColor" stroke-width="0.3" opacity="0.4"/>
            <circle cx="80" cy="28" r="3" fill="currentColor"/>
            <circle cx="80" cy="132" r="3" fill="currentColor"/>
            <circle cx="128" cy="80" r="2" fill="currentColor"/>
            <circle cx="32" cy="80" r="2" fill="currentColor"/>
            <line x1="32" y1="80" x2="128" y2="80" stroke="currentColor" stroke-width="0.3" opacity="0.4"/>
            <circle cx="80" cy="80" r="12" fill="none" stroke="currentColor" stroke-width="0.6"/>
            <circle cx="80" cy="80" r="4" fill="currentColor" opacity="0.7"/>`,
    theme: {
      glow: '#06B6D4',
      rgb: '6, 182, 212',
      streakColor: 'rgba(6, 182, 212, 0.38)',
      medallionBg: 'rgba(6, 182, 212, 0.08)',
      medallionBorder: 'rgba(6, 182, 212, 0.25)'
    },
    review: {
      user: "Dorian S.",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=60&auto=format&fit=crop&q=80",
      text: "Perfect for timing my creative sprints. A masterpiece of design."
    }
  }
];

function getFocusWeight(sp, start, end) {
  if (sp < start || sp > end) return 0;
  const mid = (start + end) / 2;
  const halfDist = (end - start) / 2;
  const linearProgress = 1.0 - Math.abs(sp - mid) / halfDist;
  return Math.sin(linearProgress * Math.PI / 2);
}

const getCardBounds = (i) => {
  if (i === 0) return { start: 0.25, end: 0.40 };
  if (i === 1) return { start: 0.40, end: 0.55 };
  if (i === 2) return { start: 0.55, end: 0.625 };
  return { start: 0.625, end: 0.70 };
};

// Shimmer streak component
function ShimmerStreak({ color, active }) {
  return (
    <div style={{
      position: 'absolute',
      top: 0,
      left: '-100%',
      width: '60%',
      height: '100%',
      background: `linear-gradient(105deg, transparent 20%, ${color} 50%, transparent 80%)`,
      opacity: active ? 0.15 : 0,
      transform: active ? 'translateX(350%)' : 'translateX(0)',
      transition: active ? 'transform 0.75s ease, opacity 0.1s ease' : 'opacity 0.4s ease',
      pointerEvents: 'none',
      zIndex: 1
    }} />
  );
}

function Card3D({ eyebrow, title, desc, glyph, actionName, index, sigil, baseAngle, idx, scrollProgress, theme }) {
  const meshRef = useRef();
  const containerRef = useRef();
  const tiltRef = useRef({ x: 0, y: 0 });
  const angleRef = useRef(baseAngle);
  const entranceProgress = useRef(0.0);
  const entranceStartedRef = useRef(false);
  const hoverProgressVal = useRef(0.0);
  const [isHovered, setIsHovered] = useState(false);
  const [shimmerActive, setShimmerActive] = useState(false);
  const sigilRef = useRef();
  const sigilAngleRef = useRef(0);
  
  const lineRef = useRef();
  const lineGeometry = useMemo(() => {
    const geom = new THREE.BufferGeometry();
    const positions = new Float32Array([0, 0, 0, 0, 0, 0]);
    geom.setAttribute('position', new THREE.BufferAttribute(positions, 3));
    return geom;
  }, []);

  // Trigger shimmer on hover
  useEffect(() => {
    if (isHovered) {
      setShimmerActive(false);
      const t = setTimeout(() => setShimmerActive(true), 30);
      return () => clearTimeout(t);
    } else {
      setShimmerActive(false);
    }
  }, [isHovered]);

  const handleMouseMove = (e) => {
    const rect = e.currentTarget.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;
    const px = (x / rect.width) - 0.5;
    const py = (y / rect.height) - 0.5;
    tiltRef.current.x = -py * 0.35;
    tiltRef.current.y = px * 0.35;
    e.currentTarget.style.setProperty('--mouse-x', `${px * 100}%`);
    e.currentTarget.style.setProperty('--mouse-y', `${py * 100}%`);
  };

  const handleMouseEnter = () => setIsHovered(true);
  const handleMouseLeave = () => {
    setIsHovered(false);
    tiltRef.current = { x: 0, y: 0 };
  };

  // Animate hover progress using GSAP for a premium smooth response
  useEffect(() => {
    gsap.to(hoverProgressVal, {
      current: isHovered ? 1.0 : 0.0,
      duration: 0.45,
      ease: "power2.out",
      overwrite: "auto"
    });
  }, [isHovered]);

  useFrame((state, delta) => {
    if (!meshRef.current) return;
    const time = state.clock.getElapsedTime();
    const sp = scrollProgress.current;

    const bounds = getCardBounds(idx);
    const focusWeight = getFocusWeight(sp, bounds.start, bounds.end);

    // Trigger entrance animation when scroll depth reaches the card's specific start range
    if (sp >= bounds.start && !entranceStartedRef.current) {
      entranceStartedRef.current = true;
      gsap.to(entranceProgress, {
        current: 1.0,
        duration: 1.0,
        ease: "power2.out"
      });
    } else if ((sp < bounds.start - 0.05 || sp < 0.08) && entranceStartedRef.current) {
      entranceStartedRef.current = false;
      gsap.to(entranceProgress, {
        current: 0.0,
        duration: 0.5,
        ease: "power2.out"
      });
    }

    const ep = entranceProgress.current;

    // Sigil slow rotation
    if (sigilRef.current) {
      sigilAngleRef.current += delta * 0.04;
      sigilRef.current.style.transform = `rotate(${sigilAngleRef.current}rad)`;
    }

    // Read GSAP-animated hover progress for 3D lift and tilt
    const hpVal = hoverProgressVal.current;

    const isMobileViewport = state.size.width < 640;
    const orbitRadius = isMobileViewport ? 3.0 : 5.2;
    const angleSpeed = 0.035 * (1.0 - focusWeight);
    angleRef.current += delta * angleSpeed;
    const orbitX = Math.cos(angleRef.current) * orbitRadius;
    const orbitY = Math.sin(angleRef.current) * (orbitRadius * 0.55);
    const orbitZ = 0.8 + Math.sin(time + idx) * 0.15;

    const cameraZ = state.camera.position.z;
    const cameraY = state.camera.position.y;
    const cameraX = state.camera.position.x;
    const focusX = cameraX;
    const focusY = cameraY + 0.12;
    const focusZ = cameraZ - 4.0;

    const targetX = THREE.MathUtils.lerp(orbitX, focusX, focusWeight);
    const targetY = THREE.MathUtils.lerp(orbitY, focusY, focusWeight);
    const targetZ = THREE.MathUtils.lerp(orbitZ, focusZ, focusWeight);

    // Apply 3D lift Y and subtle Z/Y tilt on hover
    const liftY = hpVal * 0.35;
    const tiltZ = hpVal * -0.045; // slight elegant rotation
    const tiltY = hpVal * 0.05;

    const staggerOffset = (idx % 2 === 1) ? 0.35 : 0.0;
    const targetStagger = staggerOffset * (1.0 - focusWeight);
    
    // Position if entranceProgress = 1.0 (fully spawned)
    const finalX = targetX;
    const finalY = targetY + targetStagger + liftY;
    const finalZ = targetZ;

    // Organic emergence: Lerp from [0, 0, 0] (center of orb) to [finalX, finalY, finalZ]
    const currentTargetX = THREE.MathUtils.lerp(0, finalX, ep);
    const currentTargetY = THREE.MathUtils.lerp(0, finalY, ep);
    const currentTargetZ = THREE.MathUtils.lerp(0, finalZ, ep);
    
    const entranceScaleMultiplier = THREE.MathUtils.lerp(0.01, 1.0, ep);
    const entranceRotX = (1.0 - ep) * (45 * Math.PI / 180);

    const lerpFactor = 1.0 - Math.exp(-12.0 * delta);
    meshRef.current.position.set(
      THREE.MathUtils.lerp(meshRef.current.position.x, currentTargetX, lerpFactor),
      THREE.MathUtils.lerp(meshRef.current.position.y, currentTargetY, lerpFactor),
      THREE.MathUtils.lerp(meshRef.current.position.z, currentTargetZ, lerpFactor)
    );

    let maxOtherFocus = 0;
    for (let i = 0; i < 4; i++) {
      if (i !== idx) {
        const otherBounds = getCardBounds(i);
        const fOther = getFocusWeight(sp, otherBounds.start, otherBounds.end);
        if (fOther > maxOtherFocus) maxOtherFocus = fOther;
      }
    }

    let targetOpacity = 0.32;
    if (focusWeight > 0.01) {
      targetOpacity = THREE.MathUtils.lerp(0.32, 1.0, focusWeight);
    } else if (maxOtherFocus > 0.01) {
      targetOpacity = THREE.MathUtils.lerp(0.32, 0.0, maxOtherFocus * 1.8);
    }
    
    if (sp < 0.25) {
      targetOpacity = THREE.MathUtils.lerp(0.0, targetOpacity, (sp - 0.15) / 0.10);
    }
    if (sp > 0.70) {
      targetOpacity = THREE.MathUtils.lerp(targetOpacity, 0, (sp - 0.70) / 0.08);
    }
    
    let finalOpacity = targetOpacity * ep;
    if (sp < 0.15) {
      finalOpacity = 0.0;
    }

    const mobileScaleFactor = isMobileViewport ? 0.65 : 1.0;
    const targetScale = THREE.MathUtils.lerp(1.0, 1.35, focusWeight) * entranceScaleMultiplier * mobileScaleFactor;
    const hoverScale = targetScale * (1.0 + hpVal * 0.08);
    meshRef.current.scale.setScalar(THREE.MathUtils.lerp(meshRef.current.scale.x, hoverScale, lerpFactor));
    meshRef.current.rotation.x = THREE.MathUtils.lerp(meshRef.current.rotation.x, tiltRef.current.x + entranceRotX, lerpFactor);
    meshRef.current.rotation.y = THREE.MathUtils.lerp(meshRef.current.rotation.y, tiltRef.current.y + tiltY, lerpFactor);
    meshRef.current.rotation.z = THREE.MathUtils.lerp(meshRef.current.rotation.z, tiltZ, lerpFactor);

    if (containerRef.current) {
      containerRef.current.style.opacity = finalOpacity;
      containerRef.current.style.pointerEvents = finalOpacity > 0.15 ? 'auto' : 'none';
    }

    // Dynamic Line Connector Updates
    if (lineRef.current) {
      const posAttr = lineRef.current.geometry.attributes.position;
      posAttr.setXYZ(1, meshRef.current.position.x, meshRef.current.position.y, meshRef.current.position.z);
      posAttr.needsUpdate = true;
      lineRef.current.material.opacity = finalOpacity * 0.5;
    }
  });

  return (
    <group>
      {/* 3D Cosmic Connection Line */}
      <line ref={lineRef} geometry={lineGeometry}>
        <lineBasicMaterial 
          color={theme.glow} 
          transparent 
          opacity={0} 
          blending={THREE.AdditiveBlending}
          depthWrite={false}
        />
      </line>

      {/* 3D Card Mesh */}
      <mesh ref={meshRef}>
        <planeGeometry args={[1.2, 1.68]} />
        <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        <Html center distanceFactor={5.5} style={{ willChange: 'opacity, transform', pointerEvents: 'none' }}>
        <div
          ref={containerRef}
          onMouseMove={handleMouseMove}
          onMouseEnter={handleMouseEnter}
          onMouseLeave={handleMouseLeave}
          onClick={() => window.dispatchEvent(new CustomEvent('open-generator'))}
          style={{
            width: '270px',
            height: '380px',
            position: 'relative',
            cursor: 'pointer',
            fontFamily: "'Inter', 'SF Pro Display', system-ui, sans-serif",
            borderRadius: '20px',
            transition: 'border-color 0.4s ease, box-shadow 0.4s ease',
            zIndex: 1,
            // Strict frosted glass recipe with high-contrast backing plate:
            background: 'rgba(10, 8, 28, 0.72)',
            backdropFilter: 'blur(25px)',
            WebkitBackdropFilter: 'blur(25px)',
            border: isHovered ? '1px solid rgba(255, 255, 255, 0.22)' : '1px solid rgba(255, 255, 255, 0.09)',
            boxShadow: isHovered 
              ? `0 25px 55px rgba(0, 0, 0, 0.55), 0 0 35px rgba(${theme.rgb}, 0.62), 0 0 90px rgba(147, 51, 234, 0.28), inset 0 0 15px rgba(255, 255, 255, 0.06)`
              : `0 12px 28px rgba(0, 0, 0, 0.45), 0 0 20px rgba(${theme.rgb}, 0.32), 0 0 60px rgba(147, 51, 234, 0.12), inset 0 0 10px rgba(255, 255, 255, 0.03)`,
            display: 'flex',
            flexDirection: 'column',
            overflow: 'hidden',
            transformStyle: 'preserve-3d',
            perspective: '1000px',
            opacity: 0,
            pointerEvents: 'none'
          }}
        >
          {/* Reflection Gloss Overlay (Dynamic reflection that follows cursor) */}
          <div style={{
            position: 'absolute',
            inset: 0,
            background: 'radial-gradient(circle at calc(50% + var(--mouse-x, 0%)) calc(50% + var(--mouse-y, 0%)), rgba(255, 255, 255, 0.08) 0%, transparent 60%)',
            pointerEvents: 'none',
            zIndex: 3,
            opacity: isHovered ? 1 : 0,
            transition: 'opacity 0.4s ease'
          }} />

          {/* Layered soft internal ambient glows (Specific card accent blended with cosmic purple) */}
          <div style={{
            position: 'absolute',
            top: '-50px',
            left: '-50px',
            width: '200px',
            height: '200px',
            background: `radial-gradient(circle, rgba(${theme.rgb}, ${isHovered ? 0.22 : 0.12}) 0%, transparent 70%)`,
            pointerEvents: 'none',
            zIndex: 0,
            transition: 'background 0.4s ease'
          }} />
          <div style={{
            position: 'absolute',
            bottom: '-50px',
            right: '-50px',
            width: '200px',
            height: '200px',
            background: `radial-gradient(circle, rgba(147, 51, 234, ${isHovered ? 0.08 : 0.04}) 0%, transparent 70%)`,
            pointerEvents: 'none',
            zIndex: 0,
            transition: 'background 0.4s ease'
          }} />

          {/* Internal floating card-specific color particles */}
          {isHovered && Array.from({ length: 9 }).map((_, i) => {
            const left = 15 + Math.random() * 240;
            const bottom = 10 + Math.random() * 45;
            const delay = i * 0.18;
            const scale = 0.5 + Math.random() * 0.8;
            return (
              <div 
                key={i} 
                className="luxury-card-particle-internal" 
                style={{ 
                  left: `${left}px`, 
                  bottom: `${bottom}px`, 
                  animationDelay: `${delay}s`,
                  transform: `scale(${scale})`,
                  background: theme.glow,
                  boxShadow: `0 0 6px ${theme.glow}, 0 0 12px rgba(${theme.rgb}, 0.45)`
                }} 
              />
            );
          })}

          {/* External orbiting glow particles (Specific card theme + cosmic purple) */}
          {isHovered && Array.from({ length: 4 }).map((_, i) => {
            const positions = [
              { top: '-15px', left: '-15px' },
              { top: '-15px', right: '-15px' },
              { bottom: '-15px', left: '-15px' },
              { bottom: '-15px', right: '-15px' }
            ];
            const delay = i * 0.4;
            const isCardColor = i % 2 === 0;
            return (
              <div 
                key={i} 
                className="luxury-card-particle-external" 
                style={{ 
                  position: 'absolute',
                  ...positions[i],
                  animationDelay: `${delay}s`,
                  background: isCardColor ? theme.glow : '#A855F7',
                  boxShadow: isCardColor 
                    ? `0 0 8px ${theme.glow}, 0 0 16px rgba(${theme.rgb}, 0.6)` 
                    : '0 0 8px #A855F7, 0 0 16px rgba(168, 85, 247, 0.6)'
                }} 
              />
            );
          })}

          {/* Corner bracket accents — top-left */}
          <div style={{
            position: 'absolute',
            top: '12px',
            left: '12px',
            width: '18px',
            height: '18px',
            borderTop: `1.2px solid ${theme.glow}`,
            borderLeft: `1.2px solid ${theme.glow}`,
            opacity: isHovered ? 0.95 : 0.4,
            transition: 'opacity 0.3s ease',
            zIndex: 10,
            borderRadius: '2px 0 0 0'
          }} />
          {/* Corner bracket — bottom-right */}
          <div style={{
            position: 'absolute',
            bottom: '12px',
            right: '12px',
            width: '18px',
            height: '18px',
            borderBottom: `1.2px solid ${theme.glow}`,
            borderRight: `1.2px solid ${theme.glow}`,
            opacity: isHovered ? 0.95 : 0.4,
            transition: 'opacity 0.3s ease',
            zIndex: 10,
            borderRadius: '0 0 2px 0'
          }} />

          {/* Roman numeral index — top right */}
          <div style={{
            position: 'absolute',
            top: '16px',
            right: '20px',
            fontFamily: "'Georgia', 'Times New Roman', serif",
            fontSize: '9.5px',
            letterSpacing: '0.15em',
            color: theme.glow,
            opacity: 0.8,
            zIndex: 10,
            fontStyle: 'italic',
            textShadow: `0 0 8px ${theme.glow}`
          }}>
            {index}
          </div>

          {/* Main content wrapper with parallax 3D depth */}
          <div style={{
            position: 'absolute',
            inset: '0px',
            borderRadius: '19px',
            background: 'transparent',
            overflow: 'hidden',
            zIndex: 1,
            display: 'flex',
            flexDirection: 'column',
            transform: isHovered ? 'translateZ(20px)' : 'translateZ(0px)',
            transition: 'transform 0.45s cubic-bezier(0.25, 1, 0.5, 1)',
            transformStyle: 'preserve-3d'
          }}>
            {/* Shimmer streak */}
            <ShimmerStreak color={theme.streakColor} active={shimmerActive} />

            {/* Sigil background — rotates slowly */}
            <div
              ref={sigilRef}
              style={{
                position: 'absolute',
                bottom: '20px',
                right: '-20px',
                width: '160px',
                height: '160px',
                opacity: isHovered ? 0.14 : 0.06,
                transition: 'opacity 0.5s ease',
                color: theme.glow,
                pointerEvents: 'none',
                zIndex: 0
              }}
            >
              <svg viewBox="0 0 160 160" xmlns="http://www.w3.org/2000/svg" width="160" height="160"
                dangerouslySetInnerHTML={{ __html: sigil }}
                style={{ color: theme.glow }}
              />
            </div>

            {/* UI Content Layer */}
            <div style={{
              position: 'relative',
              zIndex: 5,
              padding: '20px 20px 18px',
              display: 'flex',
              flexDirection: 'column',
              height: '100%',
              gap: '0',
              transformStyle: 'preserve-3d'
            }}>
              {/* Icon medallion with glowing glyph */}
              <div style={{
                width: '40px',
                height: '40px',
                borderRadius: '50%',
                background: theme.medallionBg,
                border: `1.2px solid ${theme.medallionBorder}`,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                marginBottom: '12px',
                boxShadow: isHovered ? `0 0 20px rgba(${theme.rgb}, 0.28)` : 'none',
                transition: 'all 0.4s ease',
                transform: isHovered ? 'translateZ(25px)' : 'translateZ(0px)'
              }}>
                <span style={{
                  fontSize: '18px',
                  color: isHovered ? '#FFD700' : '#C084FC',
                  textShadow: isHovered ? '0 0 10px rgba(255, 215, 0, 0.7)' : 'none',
                  transition: 'all 0.4s ease',
                  fontFamily: 'serif',
                  lineHeight: 1
                }}>
                  {glyph}
                </span>
              </div>

              {/* Eyebrow - Category/Theme */}
              <div style={{
                fontFamily: "'Inter', sans-serif",
                fontSize: '9px',
                fontWeight: 600,
                letterSpacing: '0.18em',
                color: theme.glow,
                textTransform: 'uppercase',
                marginBottom: '4px',
                opacity: isHovered ? 1.0 : 0.75,
                transition: 'opacity 0.3s ease, color 0.3s ease',
                textShadow: isHovered ? `0 0 8px ${theme.glow}` : 'none'
              }}>
                {eyebrow}
              </div>

              {/* Title — Cinzel engraved serif */}
              <div style={{
                fontSize: '13.5px',
                fontWeight: 600,
                letterSpacing: '0.1em',
                color: '#FFFFFF', // pure white for maximum high-contrast visibility
                lineHeight: 1.25,
                marginBottom: '8px',
                textTransform: 'uppercase',
                fontFamily: "'Cinzel', 'Trajan Pro', 'Times New Roman', serif",
                textShadow: isHovered ? '0 0 10px rgba(255, 255, 255, 0.3)' : 'none',
                transform: isHovered ? 'translateZ(15px)' : 'translateZ(0px)',
                transition: 'text-shadow 0.4s ease, transform 0.45s ease'
              }}>
                {title}
              </div>

              {/* Sigil glyph divider — ✦ ✦ ✦ between fading lines */}
              <div style={{
                display: 'flex',
                alignItems: 'center',
                gap: '7px',
                marginBottom: '10px',
              }}>
                <div style={{
                  flex: 1,
                  height: '1px',
                  background: `linear-gradient(90deg, transparent, ${theme.glow})`,
                  opacity: isHovered ? 0.95 : 0.6,
                  transition: 'opacity 0.4s ease',
                }} />
                <span style={{
                  fontSize: '7px',
                  letterSpacing: '0.32em',
                  color: theme.glow,
                  opacity: isHovered ? 1 : 0.75,
                  transition: 'opacity 0.4s ease',
                  flexShrink: 0,
                  lineHeight: 1,
                  paddingRight: '0.32em',
                }}>✦ ✦ ✦</span>
                <div style={{
                  flex: 1,
                  height: '1px',
                  background: `linear-gradient(90deg, ${theme.glow}, transparent)`,
                  opacity: isHovered ? 0.95 : 0.6,
                  transition: 'opacity 0.4s ease',
                }} />
              </div>

              {/* Description — Inter, clean and highly readable Slate-200 */}
              <p style={{
                fontSize: '11.5px',
                lineHeight: 1.55,
                color: '#E2E8F0', // slate 200 for excellent visibility against dark backdrop
                margin: 0,
                fontFamily: "'Inter', 'SF Pro Text', system-ui, sans-serif",
                fontWeight: 400,
                letterSpacing: '0.01em',
                flex: 1,
              }}>
                {desc}
              </p>

              {/* User Review / Testimonial Block */}
              <div style={{
                marginTop: '10px',
                marginBottom: '12px',
                padding: '8px 10px',
                borderRadius: '8px',
                background: 'rgba(255, 255, 255, 0.03)',
                border: '1px solid rgba(255, 255, 255, 0.05)',
                display: 'flex',
                flexDirection: 'column',
                gap: '5px'
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <img 
                    src={cardData[idx].review.avatar} 
                    alt={cardData[idx].review.user}
                    style={{
                      width: '20px',
                      height: '20px',
                      borderRadius: '50%',
                      objectFit: 'cover',
                      border: `1.2px solid rgba(${theme.rgb}, 0.5)`,
                      boxShadow: `0 0 8px rgba(${theme.rgb}, 0.35)`
                    }}
                  />
                  <div style={{ display: 'flex', flexDirection: 'column' }}>
                    <span style={{ fontSize: '9px', fontWeight: 600, color: '#F1F5F9', lineHeight: 1.1 }}>
                      {cardData[idx].review.user}
                    </span>
                    <span style={{ fontSize: '8px', color: '#F59E0B', letterSpacing: '1px', lineHeight: 1.1 }}>
                      ★★★★★
                    </span>
                  </div>
                </div>
                <p style={{
                  fontSize: '9px',
                  lineHeight: '1.35',
                  color: '#94A3B8',
                  margin: 0,
                  fontStyle: 'italic'
                }}>
                  "{cardData[idx].review.text}"
                </p>
              </div>

              {/* CTA row */}
              <div style={{
                marginTop: 'auto',
                paddingTop: '12px',
                borderTop: `1px solid rgba(${theme.rgb}, ${isHovered ? '0.22' : '0.1'})`,
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                transition: 'border-color 0.4s ease',
              }}>
                <div style={{
                  width: '5px',
                  height: '5px',
                  borderRadius: '50%',
                  background: theme.glow,
                  boxShadow: `0 0 7px ${theme.glow}, 0 0 14px rgba(${theme.rgb}, 0.55)`,
                  flexShrink: 0,
                }} />
                <span style={{
                  fontSize: '9.5px',
                  fontWeight: 600,
                  letterSpacing: '0.2em',
                  textTransform: 'uppercase',
                  fontFamily: "'Inter', system-ui, sans-serif",
                  color: isHovered ? '#FFFFFF' : '#94A3B8', // High contrast whites/slates
                  transition: 'color 0.3s ease',
                }}>
                  {actionName}
                </span>
                <div style={{
                  marginLeft: 'auto',
                  width: '24px',
                  height: '24px',
                  borderRadius: '50%',
                  border: `1.2px solid ${isHovered ? theme.glow : 'rgba(255, 255, 255, 0.18)'}`,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  transition: 'border-color 0.3s ease, box-shadow 0.3s ease, background 0.3s ease',
                  boxShadow: isHovered ? `0 0 10px rgba(${theme.rgb}, 0.5)` : 'none',
                  background: isHovered ? `rgba(${theme.rgb}, 0.1)` : 'transparent'
                }}>
                  <span style={{
                    fontSize: '11px',
                    color: isHovered ? '#FFFFFF' : 'rgba(255, 255, 255, 0.5)',
                    transition: 'color 0.3s ease, transform 0.3s ease',
                    display: 'block',
                    transform: isHovered ? 'translateX(1.5px)' : 'none',
                  }}>→</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </Html>
      </mesh>
    </group>
  );
}

export default function FloatingCards({ scrollProgress }) {
  return (
    <group>
      {cardData.map((card, idx) => (
        <Card3D
          key={idx}
          eyebrow={card.eyebrow}
          title={card.title}
          glyph={card.glyph}
          desc={card.desc}
          actionName={card.actionName}
          index={card.index}
          sigil={card.sigil}
          baseAngle={card.baseAngle}
          idx={idx}
          scrollProgress={scrollProgress}
          theme={card.theme}
        />
      ))}
    </group>
  );
}
